#!/bin/bash
#PBS -N oe_GEMMA_Plot
#PBS -l select=1:ncpus=3:mem=125gb,walltime=72:00:00
#PBS -j oe


echo "START ------------------------------"

module add anaconda
source activate r_env_360
##lib_r360='.libPaths(c('~/.conda/envs/r_env_360/lib', .libPaths()))'
#src='/panicle/ssapkot/GrainComp/'
#
#DESIGN_FILE='/scratch2/ssapkot/GrainComp/doc/CV_seeds.txt'
#DESIGN=$(cat ${DESIGN_FILE} | head -n ${PBS_ARRAY_INDEX} | tail -n 1)
#
#IFS=',' read -ra ARRAY <<< "${DESIGN}"
#
#TRAIT="${ARRAY[0]}"
###MODEL="${ARRAY[1]}"
#
###Rscript  <$src/scripts/CV_Bayesian_BGLR.R
export LD_LIBRARY_PATH=/home/ssapkot/.conda/envs/r_env_360/lib/:$LD_LIBRARY_PATH

R -e "

#.libPaths(c('/home/ssapkot/.conda/envs/r_env_360/lib', .libPaths()))

library(lattice)
library(ggplot2)
library(dplyr)
library(ggrepel)

setwd('/panicle/ssapkot/GrainComp/GEMMA/')

file = read.table('Amylose_Parameters_mean.txt', stringsAsFactors=FALSE, sep='\t', header=TRUE)

gwas.sig <- file[file\$gamma > 0.01,]
mysnps <- gwas.sig\$RS

print(head(gwas.sig))
write.csv(gwas.sig, '/panicle/ssapkot/GrainComp/GEMMA/Results/Amylose_BSLMM_SelectedSNPs_plots.csv', row.names=FALSE)

#file\$adj.P <- p.adjust(file\$gamma, method = 'bonferroni') ##bonferroni-correction
sig <- 0.01
sugg <- 0.01

gg.manhattan <- function(df, threshold, hlight, ylims, title){
nCHR <- length(unique(df\$CHR))
df\$BPcum <- NA
s <- 0
nbp <- c()
for (i in unique(df\$CHR)){
      nbp[i] <- max(df[df\$CHR == i,]\$PS)
        df[df\$CHR == i,'BPcum'] <- df[df\$CHR == i,'PS'] + s
          s <- s + nbp[i]
      }

###Setting up the parameters and axis
axis.set <- df %>% 
  group_by(CHR) %>% 
    summarize(center = (max(BPcum) + min(BPcum)) / 2)
    
   # ylim <- abs(floor(log10(min(df\$gamma)))) + 2

    df.tmp <- df %>%
         # Add highlight and annotation information
            mutate( is_highlight=ifelse(RS %in% hlight, 'yes', 'no')) %>%
            mutate( is_annotate=ifelse(gamma > threshold, 'yes', 'no'))

  ggplot(df.tmp, aes(x=BPcum, y=gamma)) +
    geom_point(aes(color=as.factor(CHR)), alpha = 0.8, size = 2) +
    ##add highlighted points
    geom_point(data=subset(df.tmp, is_highlight=='yes'), color='orange', size=2) +
    
    #custom axes
    scale_color_manual(values = rep(c('darkslateblue','cadetblue'), nCHR)) +
    scale_x_continuous(label = axis.set\$CHR, breaks = axis.set\$center) +
    scale_y_continuous(expand = c(0,0), limits = ylims) +
    
    # add genome-wide significant and suggested lines
    #geom_hline(yintercept = -log10(sig), color = 'darkgreen', linetype = 'dashed') + 
    geom_hline(yintercept = sig, color = 'blue', linetype = 'dashed') +
    
    ggtitle(paste0(title)) +
    labs(x = NULL, y = 'BSLMM PIP') +

    # Add label using ggrepel to avoid overlapping
    geom_label_repel(data=df.tmp[df.tmp\$is_annotate=='yes',], aes(label=as.factor(RS), alpha=0.7), size=5, force=1.3) + 

    #customize the theme
    theme_bw(base_size=20) +
    theme( 
    legend.position = 'none',
    panel.border = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 0,  vjust = 0.5)
    )
#ggsave('Manhattanplot_Amylose_BSLMM_bonferroni.png', manhplot, width = 30, height = 5, units = 'cm')
}

png('/panicle/ssapkot/GrainComp/GEMMA/Results/Manhattanplot_Amylose_BSLMM_annotated.png', width=1425, height=975)
print(gg.manhattan(file,sugg, mysnps, c(0,),'MV GWAS Starch Protein'))
dev.off()

"
echo "Finish__________________"

